In [137]:
import pandas as pd
import numpy as np

In [138]:
pokemon = pd.read_csv("pokemon.csv")
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [139]:
display(pokemon.head(10))

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
9,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [140]:
import re

In [141]:
pokemon.columns
list(pokemon.columns)

for col in pokemon.columns:
     # do something with a column name;
    print(col)

#
Name
Type 1
Type 2
Total
HP
Attack
Defense
Sp. Atk
Sp. Def
Speed
Generation
Legendary

In [142]:
%%time
# this returns an iterable index object
pokemon.index

CPU times: total: 0 ns
Wall time: 0 ns

RangeIndex(start=0, stop=800, step=1)

In [143]:
pokemon.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [144]:
pokemon[['Name', 'Type 1', 'Type 2']]

                      Name   Type 1  Type 2
0                Bulbasaur    Grass  Poison
1                  Ivysaur    Grass  Poison
2                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
795                Diancie     Rock   Fairy
796    DiancieMega Diancie     Rock   Fairy
797    HoopaHoopa Confined  Psychic   Ghost
798     HoopaHoopa Unbound  Psychic    Dark
799              Volcanion     Fire   Water

[800 rows x 3 columns]

In [156]:
pokemon['Type 1'].unique()

array(['Grass', 'Fire', 'Water', 'Bug', 'Normal', 'Poison', 'Electric',
       'Ground', 'Fairy', 'Fighting', 'Psychic', 'Rock', 'Ghost', 'Ice',
       'Dragon', 'Dark', 'Steel', 'Flying'], dtype=object)

In [146]:
pokemon['Type 2'].unique()

array(['Poison', nan, 'Flying', 'Dragon', 'Ground', 'Fairy', 'Grass',
       'Fighting', 'Psychic', 'Steel', 'Ice', 'Rock', 'Dark', 'Water',
       'Electric', 'Fire', 'Ghost', 'Bug', 'Normal'], dtype=object)

In [147]:
pokemon.Name = pokemon.Name.apply(lambda x: re.sub(r'(.+)(Mega.+)',r'\2', x))
pokemon.Name = pokemon.Name.apply(lambda x: re.sub(r'(.+)(Prima1.+)',r'\2', x))
pokemon.Name = pokemon.Name.apply(lambda x: re.sub(r'(HoopaHoopa)(.+)','Hoopa'+r'\2', x))

In [157]:
print(pd.concat([pokemon['Type 1'], pokemon['Type 2']]).unique())
len(pd.concat([pokemon['Type 1'], pokemon['Type 2']]).unique())

['Grass' 'Fire' 'Water' 'Bug' 'Normal' 'Poison' 'Electric' 'Ground'
 'Fairy' 'Fighting' 'Psychic' 'Rock' 'Ghost' 'Ice' 'Dragon' 'Dark' 'Steel'
 'Flying' '']

19

In [159]:
display(sorted(dict(pokemon['Type 1'].value_counts()).items()))

display(sorted(dict(pokemon['Type 2'].value_counts()).items()))

[('Bug', 69),
 ('Dark', 31),
 ('Dragon', 32),
 ('Electric', 44),
 ('Fairy', 17),
 ('Fighting', 27),
 ('Fire', 52),
 ('Flying', 4),
 ('Ghost', 32),
 ('Grass', 70),
 ('Ground', 32),
 ('Ice', 24),
 ('Normal', 98),
 ('Poison', 28),
 ('Psychic', 57),
 ('Rock', 44),
 ('Steel', 27),
 ('Water', 112)]

[('', 386),
 ('Bug', 3),
 ('Dark', 20),
 ('Dragon', 18),
 ('Electric', 6),
 ('Fairy', 23),
 ('Fighting', 26),
 ('Fire', 12),
 ('Flying', 97),
 ('Ghost', 14),
 ('Grass', 25),
 ('Ground', 35),
 ('Ice', 14),
 ('Normal', 4),
 ('Poison', 34),
 ('Psychic', 33),
 ('Rock', 14),
 ('Steel', 22),
 ('Water', 14)]

In [161]:
print(len(pokemon))
type_columns = ['Type 1', 'Type 2']
types = pokemon[type_columns].drop_duplicates()
display(types)

800

      Type 1  Type 2
0      Grass  Poison
4       Fire
6       Fire  Flying
7       Fire  Dragon
9      Water
..       ...     ...
778    Ghost   Grass
790   Flying  Dragon
797  Psychic   Ghost
798  Psychic    Dark
799     Fire   Water

[154 rows x 2 columns]

In [162]:
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass Poison
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False,1.209302,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667,Rock Fairy
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545,Rock Fairy
797,720,Hoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333,Psychic Ghost
798,720,Hoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667,Psychic Dark
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667,Fire Water

In [163]:
pokemon['A/D Ratio'] = pokemon['Attack']/pokemon['Defense']
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass Poison
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False,1.209302,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667,Rock Fairy
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545,Rock Fairy
797,720,Hoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333,Psychic Ghost
798,720,Hoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667,Psychic Dark
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667,Fire Water

In [164]:
pokemon_ad = pokemon['A/D Ratio'].idxmax()
pokemon_max_ad = pokemon.loc[pokemon_ad]
print(pokemon_max_ad)

#                            386
Name          DeoxysAttack Forme
Type 1                   Psychic
Type 2
Total                        600
HP                            50
Attack                       180
Defense                       20
Sp. Atk                      180
Sp. Def                       20
Speed                        150
Generation                     3
Legendary                   True
A/D Ratio                    9.0
Combo Type              Psychic
Name: 429, dtype: object

In [151]:
pokemon_ad2 = pokemon['A/D Ratio'].idxmin()
pokemon_min_ad = pokemon.loc[pokemon_ad2]
print(pokemon_min_ad)

#                  213
Name           Shuckle
Type 1             Bug
Type 2            Rock
Total              505
HP                  20
Attack              10
Defense            230
Sp. Atk             10
Sp. Def            230
Speed                5
Generation           2
Legendary        False
A/D Ratio     0.043478
Name: 230, dtype: object

In [165]:
pokemon['Type 2'] = pokemon['Type 2'].fillna('')
pokemon['Combo Type'] = pokemon['Type 1'] + (' ' + pokemon['Type 2']).fillna(' ')
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass Poison
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False,1.209302,Fire
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,0.666667,Rock Fairy
796,719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,1.454545,Rock Fairy
797,720,Hoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,1.833333,Psychic Ghost
798,720,Hoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,2.666667,Psychic Dark
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,0.916667,Fire Water

In [166]:
pokemon_top_ratio = pokemon.nlargest(5, 'A/D Ratio')
pokemon_top_ratio

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,,600,50,180,20,180,20,150,3,True,9.000,Psychic
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug Poison
453,408,Cranidos,Rock,,350,67,125,40,30,30,58,4,False,3.125,Rock
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water Dark

In [169]:
pokemon['Combo Type'] = np.where(pokemon['Type 2'].isna(), pokemon['Type 1'], pokemon['Type 1']+'-'+pokemon['Type 2'])
pokemon.head()

# pokemon_avg = pokemon.groupby('Combo Type').mean(numeric_only=True).reset_index()
# pokemon_avg[pokemon_avg['Combo Type'].isin(pokemon_top_ratio)]
# pokemon_avg

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,1.000000,Grass-Poison
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,0.984127,Grass-Poison
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,0.987952,Grass-Poison
3,3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,0.813008,Grass-Poison
4,4,Charmander,Fire,,309,39,52,43,60,50,65,1,False,1.209302,Fire-

In [171]:
pokemon_sorted = pokemon.sort_values(by=['A/D Ratio'], ascending=False)
top_poke_list = pokemon_sorted.head(5)
top_poke_list

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,,600,50,180,20,180,20,150,3,True,9.000,Psychic-
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
453,408,Cranidos,Rock,,350,67,125,40,30,30,58,4,False,3.125,Rock-
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water-Dark

In [173]:
combo_list = list(top_poke_list['Combo Type'].unique())
combo_list

['Psychic-', 'Water-Dark', 'Bug-Poison', 'Rock-']

In [176]:
top_combos = pokemon_sorted.iloc[0:5]

combo_types = top_combos['Combo Type'].unique()
list_combotypes = list(combo_types)

top_combos

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio,Combo Type
429,386,DeoxysAttack Forme,Psychic,,600,50,180,20,180,20,150,3,True,9.000,Psychic-
347,318,Carvanha,Water,Dark,305,45,90,20,65,20,65,3,False,4.500,Water-Dark
19,15,Mega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False,3.750,Bug-Poison
453,408,Cranidos,Rock,,350,67,125,40,30,30,58,4,False,3.125,Rock-
348,319,Sharpedo,Water,Dark,460,70,120,40,95,40,95,3,False,3.000,Water-Dark

In [179]:
poke_mean = pokemon_sorted.groupby('Combo Type').agg('mean').reset_index()
poke_mean

C:\Users\harri\AppData\Local\Temp\ipykernel_14528\463658210.py:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  poke_mean = pokemon_sorted.groupby('Combo Type').agg('mean').reset_index()

,Combo Type,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
0,Bug-,361.352941,289.705882,53.058824,50.352941,55.411765,39.294118,43.647059,47.941176,3.470588,0.0,0.940179
1,Bug-Electric,595.500000,395.500000,60.000000,62.000000,55.000000,77.000000,55.000000,86.500000,5.000000,0.0,1.111667
2,Bug-Fighting,214.000000,550.000000,80.000000,155.000000,95.000000,40.000000,100.000000,80.000000,2.000000,0.0,1.637681
3,Bug-Fire,636.500000,455.000000,70.000000,72.500000,60.000000,92.500000,80.000000,80.000000,5.000000,0.0,1.234266
4,Bug-Flying,286.285714,419.500000,63.000000,70.142857,61.571429,72.857143,69.071429,82.857143,2.857143,0.0,1.146274
...,...,...,...,...,...,...,...,...,...,...,...,...
149,Water-Ice,103.000000,511.666667,90.000000,83.333333,113.333333,80.000000,78.333333,66.666667,1.000000,0.0,0.821759
150,Water-Poison,118.666667,426.666667,61.666667,68.333333,58.333333,61.666667,91.666667,85.000000,1.333333,0.0,1.162149
151,Water-Psychic,111.800000,481.000000,87.000000,73.000000,104.000000,94.000000,79.000000,44.000000,1.200000,0.0,0.783668
152,Water-Rock,430.000000,428.750000,70.750000,82.750000,112.750000,61.500000,65.000000,36.000000,3.750000,0.0,0.727170
153,Water-Steel,395.000000,530.000000,84.000000,86.000000,88.000000,111.000000,101.000000,60.000000,4.000000,0.0,0.977273

In [180]:
poke_mean[poke_mean['Combo Type'].isin(list_combotypes)]

,Combo Type,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,A/D Ratio
8,Bug-Poison,199.166667,347.916667,53.750000,68.333333,58.083333,42.500000,59.333333,65.916667,2.333333,0.000000,1.315989
109,Psychic-,381.973684,464.552632,72.552632,64.947368,67.236842,98.552632,82.394737,78.868421,3.342105,0.236842,1.164196
117,Rock-,410.111111,409.444444,67.111111,103.333333,107.222222,40.555556,58.333333,32.888889,3.888889,0.111111,1.260091
140,Water-Dark,347.666667,493.833333,69.166667,120.000000,65.166667,88.833333,63.500000,87.166667,3.166667,0.000000,2.291949